---
runtime: shiny
title: "OncoReporter"
subtitle: 'Informe de variantes'
author: "Raquel Romero Garcia"
date: '`r format(Sys.Date(),"%e de %B, %Y")`' 
output:
 prettydoc::html_pretty:
    theme: cayman
params:
  sexo:
    label: "Selecciona el sexo"
    value: NA
    input: select
    choices: [Masculino, Femenino]
  edad:
    label: "Edad"
    value: NA
    input: text
  tumor: 
    label: "Tipo de tumor"
    value: NA
    input: text
  localizacion:
    label: "Localización"
    value: NA
    input: text
  cels_tum: 
    label: "Porcentaje de células tumorales"
    value: NA
    input: text
  datos_clasificados: 
    value: datos_clasificados

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = NULL, cache=TRUE, warning = FALSE)
```

### INFORMACIÓN GENERAL

```{r}
datos <- data.frame(c(paste0("Sexo: ", params$sexo), paste0("Edad: ", params$edad), ""),
                    c(paste0("Tipo de Tumor: ", params$tumor), paste0("Localización: ", params$localizacion),
                    paste0("Porcentaje de Células Tumorales: ",  params$cels_tum)))

# Cambiar los nombres de las columnas
colnames(datos) <- c("Paciente", "Tumor")

# Crear la tabla con el paquete kable
knitr::kable(datos)
```




### CARACTERÍSTICAS DEL ANÁLISIS

```{r}
parametros <- data.frame(c("Secuenciador: Ion Torrent", "Material secuenciado: FFPE", ""),
                    c("Método de selección: Amplificación", "Tipo de carrera: _Single End_", 
                      "Panel: _Oncomine Focus Assay_"))

# Cambiar los nombres de las columnas
colnames(parametros) <- c("", "")

knitr::kable(parametros)
```




### LISTA DE VARIANTES DETECTADAS 


```{r}
knitr::kable(params$datos_clasificados)
```



### NGS - GENES EN EL PANEL (46)

```{r}
Genes <- c ("AKT1", "ALK", "APC", "AR", "BIRC2", "BRAF", "BRCA1", "CCND1",  
"CDK4", "CTNNB1", "DCUN1D1", "DDR2", "EGFR", "ERBB2", "ERBB3", "ERBB4", 
"ESR1", "FGFR1", "FGFR2", "FGFR3", "FGFR4", "GNA11", "GNAQ", "HRAS", "IDH1", 
"IDH2", "JAK1", "JAK2", "JAK3", "KIT", "KRAS", "MAP2K1", "MAP2K2", "MED12", "MET",
"MTOR", "MYC", "MYCN", "NF1", "NRAS", "PDGFRA", "PIK3CA", "RAF1", "RET", "ROS1",
"SMO", "", "", "", "")

Genes_matriz <- matrix(Genes, nrow = 10, ncol = 5, byrow = TRUE)

# Imprimir la matriz utilizando kable
knitr::kable(Genes_matriz)
```